[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5

fs_permissions = [{ access = "read", path = "./merkleData.json" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config